main: main
name: Plugin
version: 1.0
load: STARTUP
api-version: 1.16
description: "Empty Plugin"

#commands:
#  NOM:
#    description: "§2DESCRIPTION"
#    usage: "[§6§lSystème§r] /<command> §2<sous commande>"
#    aliases: [ NOM1, NOM2 ]