main: main
name: Plugin
version: 1.0
load: STARTUP
api-version: 1.16
description: "Empty Plugin"
commands:
  test:
    description: "§2Commande de test"
    usage: "[§6§lSystème§r] /<command>"
    aliases: [ debug ]